
services:
  backend:
    build:
      context: .
      dockerfile: HRApplication.Server/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./hrapplication.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
