-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-28 14:08:21 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE applications (
    applicationid uniqueidentifier NOT NULL,
    userid        uniqueidentifier NOT NULL,
    positionid    uniqueidentifier NOT NULL,
    status        NVARCHAR(55) NOT NULL,
    submittedat   DATETIME2 NOT NULL
);

CREATE UNIQUE INDEX applications__idx ON
    applications (
        userid
    ASC );

ALTER TABLE applications ADD CONSTRAINT applications_pk PRIMARY KEY ( applicationid );

CREATE TABLE benefits (
    benefitid   uniqueidentifier NOT NULL,
    name        NVARCHAR(255) NOT NULL,
    description NVARCHAR(255) NOT NULL,
    isactive    CHAR(1) NOT NULL
);

ALTER TABLE benefits ADD CONSTRAINT benefits_pk PRIMARY KEY ( benefitid );

CREATE TABLE contractbenefits (
    contracts_contractid uniqueidentifier NOT NULL,
    benefits_benefitid   uniqueidentifier NOT NULL
);

CREATE TABLE contracts (
    contractid    uniqueidentifier NOT NULL,
    userid        uniqueidentifier NOT NULL,
    jobpositionid uniqueidentifier NOT NULL,
    contracttype  NVARCHAR(50) NOT NULL,
    startdate     DATETIME2 NOT NULL,
    enddate       DATETIME2 NOT NULL,
    salary        DECIMAL NOT NULL,
    hoursperweek  INTEGER NOT NULL,
    noticeperiod  NVARCHAR(255) NOT NULL,
    isactive      CHAR(1) NOT NULL
);

CREATE UNIQUE INDEX contracts__idx ON
    contracts (
        userid
    ASC );

ALTER TABLE contracts ADD CONSTRAINT contracts_pk PRIMARY KEY ( contractid );

CREATE TABLE employeejobpositions (
    employeejobpositionid uniqueidentifier NOT NULL,
    userid                uniqueidentifier NOT NULL,
    jobpositionid         uniqueidentifier NOT NULL,
    startdate             DATETIME2 NOT NULL,
    enddate               DATETIME2
);

CREATE UNIQUE INDEX employeejobpositions__idx ON
    employeejobpositions (
        userid
    ASC );

ALTER TABLE employeejobpositions ADD CONSTRAINT employeejobpositions_pk PRIMARY KEY ( employeejobpositionid );

CREATE TABLE jobpositions (
    jobpositionid uniqueidentifier NOT NULL,
    title         NVARCHAR(255) NOT NULL,
    description   NVARCHAR(255) NOT NULL,
    level         NVARCHAR(50) NOT NULL
);

ALTER TABLE jobpositions ADD CONSTRAINT jobpositions_pk PRIMARY KEY ( jobpositionid );

CREATE TABLE leaverequest (
    leaverequestid uniqueidentifier NOT NULL,
    userid         uniqueidentifier NOT NULL,
    leavetype      NVARCHAR(50) NOT NULL,
    startdate      DATETIME2 NOT NULL,
    enddate        DATETIME2 NOT NULL,
    status         NVARCHAR(50) NOT NULL
);

ALTER TABLE leaverequest ADD CONSTRAINT leaverequest_pk PRIMARY KEY ( leaverequestid );

CREATE TABLE loginhistory (
    loginid      uniqueidentifier NOT NULL,
    userid       uniqueidentifier NOT NULL,
    logintime    DATETIME2 NOT NULL,
    ipaddress    NVARCHAR(45) NOT NULL,
    issuccessful CHAR(1) NOT NULL,
);

ALTER TABLE loginhistory ADD CONSTRAINT loginhistory_pk PRIMARY KEY ( loginid );


CREATE TABLE recruitmentpositions (
    positionid  uniqueidentifier NOT NULL,
    title       NVARCHAR(255) NOT NULL,
    description NVARCHAR(255) NOT NULL,
    isactive    CHAR(1) NOT NULL
);

ALTER TABLE recruitmentpositions ADD CONSTRAINT recruitmentpositions_pk PRIMARY KEY ( positionid );

CREATE TABLE roles (
    roleid      uniqueidentifier NOT NULL,
    rolename    NVARCHAR(50) NOT NULL,
    description NVARCHAR(255) NOT NULL
);

ALTER TABLE roles ADD CONSTRAINT roles_pk PRIMARY KEY ( roleid );

CREATE TABLE schedule (
    scheduleid  uniqueidentifier NOT NULL,
    userid      uniqueidentifier NOT NULL,
    starttime   DATETIME2 NOT NULL,
    endtime     DATETIME2 NOT NULL,
    type        NVARCHAR(50) NOT NULL,
    description NVARCHAR(255) NOT NULL
);

ALTER TABLE schedule ADD CONSTRAINT schedule_pk PRIMARY KEY ( scheduleid );

CREATE TABLE sessions (
    sessionsid   uniqueidentifier NOT NULL,
    userid       uniqueidentifier NOT NULL,
    sessiontoken NVARCHAR(255) NOT NULL,
    expiresat    DATETIME2 NOT NULL,
    isactive     CHAR(1) NOT NULL,
    createdat    DATETIME2
);

ALTER TABLE sessions ADD CONSTRAINT sessions_pk PRIMARY KEY ( sessionsid );

CREATE TABLE teammembers (
    teammemberid uniqueidentifier NOT NULL,
    userid       uniqueidentifier NOT NULL,
    teamid       uniqueidentifier NOT NULL,
    joinedat     DATETIME2 NOT NULL,
    leftat       DATETIME2
);

ALTER TABLE teammembers ADD CONSTRAINT teammembers_pk PRIMARY KEY ( teammemberid );

CREATE TABLE teams (
    teamid    uniqueidentifier NOT NULL,
    name      NVARCHAR(255) NOT NULL,
    createdat DATETIME2 NOT NULL,
    isactive  CHAR(1) NOT NULL
);

ALTER TABLE teams ADD CONSTRAINT teams_pk PRIMARY KEY ( teamid );

CREATE TABLE trainings (
    trainingid  uniqueidentifier NOT NULL,
    title       NVARCHAR(255) NOT NULL,
    description NVARCHAR(255) NOT NULL,
    startdate   DATETIME2 NOT NULL,
    enddate     DATETIME2 NOT NULL
);

ALTER TABLE trainings ADD CONSTRAINT trainings_pk PRIMARY KEY ( trainingid );

CREATE TABLE userroles (
    userroleid uniqueidentifier NOT NULL,
    userid     uniqueidentifier NOT NULL,
    roleid     uniqueidentifier NOT NULL
);

ALTER TABLE userroles ADD CONSTRAINT userroles_pk PRIMARY KEY ( userroleid );

CREATE TABLE users (
    userid      uniqueidentifier NOT NULL,
    name        NVARCHAR(100) NOT NULL,
    surname     NVARCHAR(100) NOT NULL,
    email       NVARCHAR(255) NOT NULL,
    phonenumber NVARCHAR(15) NOT NULL,
    password    NVARCHAR(255) NOT NULL,
    createdat   DATETIME2 NOT NULL,
    updatedat   DATETIME2 NOT NULL,
    isactive    CHAR(1) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( userid );

ALTER TABLE users ADD CONSTRAINT users_email_un UNIQUE ( email );

CREATE TABLE usertrainingprogress (
    usertrainingid uniqueidentifier NOT NULL,
    userid         uniqueidentifier NOT NULL,
    trainingid     uniqueidentifier NOT NULL,
    progress       DECIMAL NOT NULL,
    lastupdated    DATETIME2 NOT NULL
);

ALTER TABLE usertrainingprogress ADD CONSTRAINT usertrainingprogress_pk PRIMARY KEY ( usertrainingid );

ALTER TABLE applications
    ADD CONSTRAINT applications_recruitmentpos_fk FOREIGN KEY ( positionid )
        REFERENCES recruitmentpositions ( positionid );

ALTER TABLE applications
    ADD CONSTRAINT applications_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE contractbenefits
    ADD CONSTRAINT contractbenefits_benefits_fk FOREIGN KEY ( benefits_benefitid )
        REFERENCES benefits ( benefitid );

ALTER TABLE contractbenefits
    ADD CONSTRAINT contractbenefits_contracts_fk FOREIGN KEY ( contracts_contractid )
        REFERENCES contracts ( contractid );

ALTER TABLE contracts
    ADD CONSTRAINT contracts_jobpositions_fk FOREIGN KEY ( jobpositionid )
        REFERENCES jobpositions ( jobpositionid );

ALTER TABLE contracts
    ADD CONSTRAINT contracts_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid )
            ON DELETE CASCADE;

ALTER TABLE employeejobpositions
    ADD CONSTRAINT employeejobpositions_jobpos_fk FOREIGN KEY ( jobpositionid )
        REFERENCES jobpositions ( jobpositionid );

ALTER TABLE employeejobpositions
    ADD CONSTRAINT employeejobpositions_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE leaverequest
    ADD CONSTRAINT leaverequest_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE loginhistory
    ADD CONSTRAINT loginhistory_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE schedule
    ADD CONSTRAINT schedule_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid )
            ON DELETE CASCADE;

ALTER TABLE sessions
    ADD CONSTRAINT sessions_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE teammembers
    ADD CONSTRAINT teammembers_teams_fk FOREIGN KEY ( teamid )
        REFERENCES teams ( teamid );

ALTER TABLE teammembers
    ADD CONSTRAINT teammembers_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );

ALTER TABLE userroles
    ADD CONSTRAINT userroles_roles_fk FOREIGN KEY ( roleid )
        REFERENCES roles ( roleid )
            ON DELETE CASCADE;

ALTER TABLE userroles
    ADD CONSTRAINT userroles_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid )
            ON DELETE CASCADE;

ALTER TABLE usertrainingprogress
    ADD CONSTRAINT usertrainingprogress_trainings_fk FOREIGN KEY ( trainingid )
        REFERENCES trainings ( trainingid );

ALTER TABLE usertrainingprogress
    ADD CONSTRAINT usertrainingprogress_users_fk FOREIGN KEY ( userid )
        REFERENCES users ( userid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             3
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
